export const MESSAGES = {
  AUTH: {
    LOGIN_SUCCESS: 'Login successful!',
    LOGIN_FAILED: 'Login failed an error occurred',
    REGISTER_FAILED: 'Registration failed.',
    REGISTER_SUCCESS:
      'Registration successful! Please check your email to verify your account.',
    LOGOUT_SUCCESS: 'Logged out successfully.',
    VERIFY_EMAIL_SUCCESS: 'Email verification successful!',
    VERIFY_EMAIL_FAILED: 'Email verification failed.',
    FORGOT_PASSWORD_SENT: 'A password reset link has been sent to your email.',
    FORGOT_PASSWORD_FAILED: 'Failed to send password reset request.',
    RESET_PASSWORD_SUCCESS:
      'Password reset successful! You can now log in with your new password.',
    RESET_PASSWORD_FAILED: 'Password reset failed.',
    VERIFY_EMAIL_EXPIRED: 'Token expired',
  },
  USER: {
    UPDATE_PROFILE_SUCCESS: 'Profile updated successfully.',
    UPDATE_PROFILE_FAILED: 'Failed to update profile.',
    CHANGE_PASSWORD_SUCCESS: 'Password changed successfully.',
    CHANGE_PASSWORD_FAILED: 'Failed to change password.',
    UPDATE_ROLE_SUCCESS: 'Role updated successfully',
    UPDATE_ROLE_FAILED: 'Failed to update role',
    UPDATE_PERMISSION_SUCCESS: 'Permission updated successfully',
    UPDATE_PERMISSION_FAILED: 'Failed to update permission',
    DELETE_PERMISSION_SUCCESS: 'Delete permission successfully',
    DELETE_PERMISSION_FAILED: 'Delete permission failed',
    MISSING_ROLE: 'Role is required',
    MISSING_PERMISSION: 'Permission is required',
    MISSING_ACTION: 'Action is required',
    MISSING_ASSIGN_ROLE: 'Assign role is required',
    UPDATE_ACTION_SUCCESS: 'Action updated successfully',
    UPDATE_ACTION_FAILED: 'Failed to update action',
  },
  BOOKING: {
    CREATE_SUCCESS: 'Booking successful!',
    CANCEL_SUCCESS: 'Booking canceled successfully.',
    ERROR: 'Unable to process your booking request.',
  },
  SYSTEM: {
    FORM_FAILED: 'Failed to submit form. Please try again',
    ERROR: 'An error occurred. Please try again later.',
  },
};