export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/me',
  FORGOT_PASSWORD: '/forgot-password',
  RESERVATION: '/reservation',
  CONTACT: '/contact',
  MENU: '/menu',
  ABOUT: '/about',
  FORBIDDEN: '/403',
    ADMIN_DASHBOARD: '/admin',
  ADMIN_HOTELS: '/admin/hotels',
  ADMIN_BOOKINGS: '/admin/bookings',
  ADMIN_USERS: '/admin/users',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_NEWS: '/admin/news',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_ROLES: '/admin/users/roles',
  ADMIN_PERMISSIONS: '/admin/users/permissions',
  ADMIN_ACTIONS: '/admin/users/actions',
  ADMIN_MENU_CATEGORIES: '/admin/menu-categories',
};